### ISSUE TITLE
Your site can't be accessed since the SSL certification expired

### ISSUE THREAD

**Issue by lwcorp** [Blazingstix/QFGImporter#3]
This is a general issue with https://blazingstix.com but I thought you might want to know.
Your site can't be accessed unless the user tells finds the "enter anyway" link in their browser.
The reason is the SSL certification expired in the middle of March, 2020.

Please renew it to keep your site alive and resume the ability to read about and download the program.

Keep in mind it only hurts your chances to appear in search engines, but that with time browsers such as Google Chrome may remove the "enter anyway" option altogether (which is not straightforward even as it is).

![image](https://user-images.githubusercontent.com/1773306/79041453-b959d700-7bf8-11ea-8a6d-403d548fd6c9.png)

![image](https://user-images.githubusercontent.com/1773306/79041469-d2628800-7bf8-11ea-8274-bb9a47741a6c.png)

**Comment by Blazingstix** [comment]
Thanks for the heads up. I'll see what I can do about renewing the cert.

**Comment by lwcorp** [comment]
Just pointing out your site is still inaccessible after all these months, this time because the certificate expired on July 10th.

**Comment by lwcorp** [comment]
Closing as it seems to be fixed now.
