### ISSUE TITLE
Can you make an online/webapp version of this program?

### ISSUE THREAD

**Issue by lwcorp** [Blazingstix/QFGImporter#5]
Just like https://qfg.azurewebsites.net except yours will be better as their version:

1. Is only for QFG1 and QFG2.
1. In QFG2, doesn't support stats that are above 200 due to the Djinn's wishes.
2. Doesn't support flags (e.g. beat Baba Yaga in QFG1, got the Sapphire Pin in QFG2) - although admittedly importing these flags don't mean much except Chainmail armor from QFG1.

**Comment by Blazingstix** [comment]
I've thought about this before, but honestly, there are only so many hours in the day and this is not something I'm personally interested in pursuing.

**Comment by lwcorp** [comment]
I hope one day you'll change your mind, as it will (relatively) reduce the risk of the program becoming unsupported with time.

Also, since you support open source, you can let others contribute to it so it won't all fall on you.
