### ISSUE TITLE
Add your site to the About section

### ISSUE THREAD

**Issue by lwcorp** [Blazingstix/QFGImporter#8]
Now that https://blazingstix.com works again (#3), could you please add it to your About?

In other words, change:
![image](https://user-images.githubusercontent.com/1773306/183241735-13db14bc-4a51-4295-b67a-2d1a2d9bc321.png)
To:
![image](https://user-images.githubusercontent.com/1773306/183241762-59fc58b1-8525-405a-a3b9-6cf04c1ab351.png)

**Comment by Blazingstix** [comment]
Thanks for the suggestion.
